#!/bin/bash

echo "🚀 MindLift GitHub Setup Guide"
echo "================================"
echo ""
echo "You have two options to push your code to GitHub:"
echo ""
echo "📝 Option 1: Create a New Repository"
echo "------------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: MindLift"
echo "3. Description: Professional Learning Platform with Role-based Dashboards"
echo "4. Make it Public or Private (your choice)"
echo "5. DO NOT initialize with README, .gitignore, or license (we have code already)"
echo "6. Click 'Create repository'"
echo ""
echo "🍴 Option 2: Fork the Original Repository"
echo "----------------------------------------"
echo "1. Go to: https://github.com/skywardcloud/MindLift"
echo "2. Click the 'Fork' button in the top right"
echo "3. This creates a copy under your account"
echo ""
echo "📤 After Creating/Forking the Repository:"
echo "---------------------------------------"
echo "Run these commands in your terminal:"
echo ""
echo "cd /Users/kunjalshukla/MindLift"
echo "git push -u origin main"
echo ""
echo "🎉 Your MindLift platform will be live on GitHub!"
echo ""
echo "📋 Repository Features:"
echo "- Complete full-stack learning platform"
echo "- Role-based dashboards (Admin, Speaker, Learner)"
echo "- Professional UI/UX design"
echo "- Comprehensive API documentation"
echo "- Test scripts and setup guides"
echo "- Production-ready code"
echo ""
echo "🔗 Your repository will be available at:"
echo "https://github.com/kshukla5/MindLift"
